### ISSUE TITLE
Separate the jQuery.ajax requirement  

### ISSUE THREAD

**Issue by pelted** [nicklandgrebe/activeresource.js#14]
I just stumbled on this looking at an alternative to rolling our own json-api client object serializer. Our backend is Rails so this looked great. The show stopper here is the reliance on jQuery for the ajax requests. We heavily use Vue.js with axios and our whole auth flow depends on that. Decoupling the request layer or allowing adapters for different options would be great.

**Comment by nicklandgrebe** [comment]
Thanks for the submission.

I'll make a formal task card for this, but know that this has been planned
for awhile and is considered an urgent release. I'll update when I've
released it

**Comment by nicklandgrebe** [comment]
This issue was solved in v1.0.0-alpha.1

https://www.npmjs.com/package/active-resource/v/1.0.0-alpha.1
