### ISSUE TITLE
Release 0.9.4 

### ISSUE THREAD

**Issue by arlaneenalra** [nicklandgrebe/activeresource.js#20]
I was looking into using your library in an application and just realized that the collections functionality I need doesn't appear until the 0.9.4 version. Unfortunately, I don't see a tag for that version or see it listed in npm.  Any idea when it will be released? Is this project currently in active development?

**Comment by nicklandgrebe** [comment]
Just published to npm. Been moving fast lately, forgot to release before moving forward!
