### ISSUE TITLE
Wrong content-type

### ISSUE THREAD

**Issue by greywolvez** [nicklandgrebe/activeresource.js#23]
If this is to be compatible with the jsonapi spec
http://jsonapi.org/format/
```
Clients MUST send all JSON API data in request documents with the header Content-Type: application/vnd.api+json without any media type parameters.
```

the content-type should be changed or allowed to be passed in.

https://github.com/nicklandgrebe/activeresource.js/blob/4d4000dfa78582a9f5f394cd37c2a8a29759ca94/src/interfaces/base.coffee#L16

**Comment by nicklandgrebe** [comment]
On it !

**Comment by nicklandgrebe** [comment]
Hey I just updated master with a commit for this issue: https://github.com/nicklandgrebe/activeresource.js/commit/52e95c28b7c4361358eabdd6ed2fb49750d06683

You can access the build at `build/active-resource.min.js`

I will release this as part of 1.0.0 soon, which will add the fix to the `dist` folder too
