### ISSUE TITLE
Date values are not posted to the server

### ISSUE THREAD

**Issue by pelletencate** [nicklandgrebe/activeresource.js#4]
To reproduce:

* Build (or fetch) a resource, and set one of its fields to `new Date`
* Save the resource

Expected:
* The date to be passed in the HTTP request to the server

Actual
* The value passed is `{}`.

**Comment by aehrmann** [comment]
@nicklandgrebe Could you look into this?

**Comment by nicklandgrebe** [comment]
#5

**Comment by nicklandgrebe** [comment]
You're gonna have to upgrade to 2.0 tho ;)
